// Generated by dts-bundle v0.7.3

declare module 'cronbee' {
    import { Scheduler } from 'cronbee/scheduler/Scheduler';
    const cronbee: Scheduler;
    export { cronbee };
}

declare module 'cronbee/scheduler/Scheduler' {
    import { IJobInfo, ICreateJob } from 'cronbee/models/IJob';
    import { IScheduler } from 'cronbee/models/IScheduler';
    export class Scheduler implements IScheduler {
        load(): Promise<IJobInfo[]>;
        ensure(params: ICreateJob): Promise<any>;
        remove(params: {
            taskName: string;
        }): Promise<any>;
    }
}

declare module 'cronbee/models/IJob' {
    export interface IJobInfo {
        name: string;
        path?: string;
        nextRun?: Date;
        enabled?: boolean;
    }
    export interface ICreateJob {
        workingDirectory?: string;
        taskName: string;
        taskRun: string;
        cron?: string;
        /** Timing flags for Schtask */
        schtaskFlags?: string;
    }
}

declare module 'cronbee/models/IScheduler' {
    import { ICreateJob, IJobInfo } from 'cronbee/models/IJob';
    export interface IScheduler {
        load(): Promise<IJobInfo[]>;
        ensure(params: ICreateJob): Promise<any>;
        remove(params: {
            taskName: string;
        }): Promise<any>;
    }
}

